### ISSUE TITLE
[BUG REPORT] 데이터 전처리 에이전트 버그

### ISSUE THREAD

**Issue by prismdata** [dataignitelab/WhaleShark_IIoT#22]
** 데이터 전처리 에이전트 실행 중 발생하는 오류를 기술하여 주시기 바랍니다.**
실행 파일: iiot_server.py 실행
발생 오류: mqtt exchange가 존재한다는 오류 발생
제안 내용: mqtt admin기능을 이용하여 메시지 서버 설정 확인 필요

**Comment by TaeKyun1980** [comment]
> ** 데이터 전처리 에이전트 실행 중 발생하는 오류를 기술하여 주시기 바랍니다.**
> 실행 파일: iiot_server.py 실행
> 발생 오류: mqtt exchange가 존재한다는 오류 발생
> 제안 내용: mqtt admin기능을 이용하여 메시지 서버 설정 확인 필요
큐와 익스체인지를 혼동한 이름 설정 문제와 함께 도커의 반응이 느린 것으로 판단되나, 동일한 오류는 아직 재현되지 않음.
