### ISSUE TITLE
수집 서버, 전처리 에이전트 공통 프로세스 로그에 time stamp 필요

### ISSUE THREAD

**Issue by prismdata-dc** [dataignitelab/WhaleShark_IIoT#30]
**설비 연동 단말, 데이터 수집 서버, 전처리 에이전트에 관한 문제점이 있다면 각 영역에 대한 기능을 요청하시기 바랍니다.**
데이터 수집 서버: 각 데이터 처리 구간에 timestamp를 적용하여야 에러 발생 시점 확인 가능
전처리 에이전트:  각 데이터 처리 구간에 timestamp를 적용하여야 에러 발생 시점 확인 가능

**Comment by TaeKyun1980** [comment]
> **설비 연동 단말, 데이터 수집 서버, 전처리 에이전트에 관한 문제점이 있다면 각 영역에 대한 기능을 요청하시기 바랍니다.**
> 데이터 수집 서버: 각 데이터 처리 구간에 timestamp를 적용하여야 에러 발생 시점 확인 가능
> 전처리 에이전트: 각 데이터 처리 구간에 timestamp를 적용하여야 에러 발생 시점 확인 가능
로그에 출력 시간 기록하였음.
