### ISSUE TITLE
[BUG REPORT]

### ISSUE THREAD

**Issue by TaeKyun1980** [dataignitelab/WhaleShark_IIoT#42]
** 데이터 수집 엔진 실행 중 발생하는 오류를 기술하여 주시기 바랍니다.**
실행 파일: iiot_mqtt_agent.py 실행
발생 오류: influxdb의 table이 가진 필드 중 postfix가 _1인 필드가 자동생성됨
제안 내용: debugging 필요

**Comment by prismdata-dc** [comment]
influxdb의 tag와 field name이 동일하게 설정되어 있어 발생하는 문제로 판단됩니다.
tag를 삭제하여 테스트를 해봐야 할 듯 하네요.
ref) https://github.com/influxdata/influxdb/issues/9891

**Comment by prismdata-dc** [comment]
> influxdb의 tag와 field name이 동일하게 설정되어 있어 발생하는 문제로 판단됩니다.
> tag를 삭제하여 테스트를 해봐야 할 듯 하네요.
> ref) [influxdata/influxdb#9891](https://github.com/influxdata/influxdb/issues/9891)

필드와 테그에 동시에 같은 이름을 적용하여 발생하는 문제로 판단되며 현재는 해당 이슈가 사라졌습니다.
