### ISSUE TITLE
코드 동작 테스트를 위한 에뮬레이터 필요

### ISSUE THREAD

**Issue by prismdata-dc** [dataignitelab/WhaleShark_IIoT#44]
데이터 수집과 전처리 프로세스 테스트를 위해 단말 역할을 하는 에뮬레이터가 요구됨.

**Comment by TaeKyun1980** [comment]
> 데이터 수집과 전처리 프로세스 테스트를 위해 단말 역할을 하는 에뮬레이터가 요구됨.

csv벡업 데이터를 기반으로 정상 작동되고 있음.

**Comment by prismdata-dc** [comment]
다중 설비 오류 발생 전까지 해당 이슈는 임시로 닫습니다.
